Image.create!([
  {filepicker_url: "https://www.filepicker.io/api/file/heQj8caSSLGmiyxdWXvb", alt_tag: nil, imageable_id: 1, imageable_type: "User"},
  {filepicker_url: "https://www.filepicker.io/api/file/Kfcrx6ESQGuHfy3SB3YM", alt_tag: nil, imageable_id: 2, imageable_type: "User"},
  {filepicker_url: "https://www.filepicker.io/api/file/hNohGDQS7mfe0UWI3mYa", alt_tag: nil, imageable_id: 3, imageable_type: "User"},
  {filepicker_url: "https://www.filepicker.io/api/file/Y1FBkWb6Sn6yuQhnqsv9", alt_tag: nil, imageable_id: 4, imageable_type: "User"},
  {filepicker_url: "https://www.filepicker.io/api/file/9WKLKQLtTYuNEyoIeU01", alt_tag: nil, imageable_id: 5, imageable_type: "User"},
  {filepicker_url: "https://www.filepicker.io/api/file/aj95Q79gRmHGIhPwRHIA", alt_tag: nil, imageable_id: 6, imageable_type: "User"},
  {filepicker_url: "https://www.filepicker.io/api/file/M9HJxoiwSPWh40FRLNYK", alt_tag: nil, imageable_id: 7, imageable_type: "User"},
  {filepicker_url: "https://www.filepicker.io/api/file/E5GjJ7IpSoyZM1PutFmj", alt_tag: nil, imageable_id: 8, imageable_type: "User"},
  {filepicker_url: "https://www.filepicker.io/api/file/Vjs9MgMVQqWnCaxW7SbM", alt_tag: nil, imageable_id: 10, imageable_type: "User"},
  {filepicker_url: "https://www.filepicker.io/api/file/H79yy9rpTpWNGrmog7xV", alt_tag: nil, imageable_id: 11, imageable_type: "User"},
  {filepicker_url: "https://www.filepicker.io/api/file/S3EwvoOAQV6deTqljJLL", alt_tag: nil, imageable_id: 12, imageable_type: "User"},
  {filepicker_url: "https://www.filepicker.io/api/file/QpyvxvzwQoKiMHkMEdg5", alt_tag: nil, imageable_id: 1, imageable_type: "Lair"},
  {filepicker_url: "https://www.filepicker.io/api/file/zRG5BZPrRFePU4ziNl8G", alt_tag: nil, imageable_id: 1, imageable_type: "Lair"},
  {filepicker_url: "https://www.filepicker.io/api/file/Byglc7y9Qse0jlcI0rIn", alt_tag: nil, imageable_id: 1, imageable_type: "Lair"},
  {filepicker_url: "https://www.filepicker.io/api/file/Y9yNBZQZufyd3XY5Vz7Q", alt_tag: nil, imageable_id: 2, imageable_type: "Lair"},
  {filepicker_url: "https://www.filepicker.io/api/file/k6ZpN4mCSDSRSEDQzxHB", alt_tag: nil, imageable_id: 2, imageable_type: "Lair"},
  {filepicker_url: "https://www.filepicker.io/api/file/aaojTby7QaGTuEIooDdT", alt_tag: nil, imageable_id: 2, imageable_type: "Lair"},
  {filepicker_url: "https://www.filepicker.io/api/file/zolwvLFPRQqSH0cuPPsY", alt_tag: nil, imageable_id: 3, imageable_type: "Lair"},
  {filepicker_url: "https://www.filepicker.io/api/file/P7r4hwYvT62M2W2sbx9w", alt_tag: nil, imageable_id: 3, imageable_type: "Lair"},
  {filepicker_url: "https://www.filepicker.io/api/file/wxv22LWtRc2J8Qtbp7jI", alt_tag: nil, imageable_id: 3, imageable_type: "Lair"},
  {filepicker_url: "https://www.filepicker.io/api/file/Amu3LEGSvmGtIVO9Ynx4", alt_tag: nil, imageable_id: 4, imageable_type: "Lair"},
  {filepicker_url: "https://www.filepicker.io/api/file/orzWynBUS5yJ2hijuZs0", alt_tag: nil, imageable_id: 4, imageable_type: "Lair"},
  {filepicker_url: "https://www.filepicker.io/api/file/7I1mg3kSSW7Icho1Nxbk", alt_tag: nil, imageable_id: 4, imageable_type: "Lair"},
  {filepicker_url: "https://www.filepicker.io/api/file/Fqdi0AqmRPSnEuNw0tHl", alt_tag: nil, imageable_id: 9, imageable_type: "User"},
  {filepicker_url: "https://www.filepicker.io/api/file/sR8VlBbVRTyskyuXjtaB", alt_tag: nil, imageable_id: 5, imageable_type: "Lair"},
  {filepicker_url: "https://www.filepicker.io/api/file/FEBhpaSZaUpBAeoM9ZGg", alt_tag: nil, imageable_id: 13, imageable_type: "User"},
  {filepicker_url: "https://www.filepicker.io/api/file/R0Yle4KKTyy7RwxxFLrJ", alt_tag: nil, imageable_id: 5, imageable_type: "Lair"}
])
Lair.create!([
  {title: "Wayne Manor/ Batcave", description: "Join me in my cozy, 36 bedroom/ 20 bath manor. Wayne Manor has been in my family for generations, and is easily accessible from Gotham city via any mode of transportation, including but not limited to car, submarine, and invisible jet. If all the rooms in the main house are booked, I have a couch in the Batcave that you could probably use for a few days. ", rate: 150, owner_id: 1, lair_type: "underground", room_type: "private-room", street_address: "135 West Gate Drive", city: "Huntington", state: "NY", country: "USA", latitude: 40.8289666, longitude: -73.4484497, max_guests: 10},
  {title: "Fortress of Solitude", description: "This is, in a rather convoluted way, my ancestral home. It's just my summer home now, so it's available for use all winter long. It's a little out of the way, but you won't find quieter neighbors. I definitely recommend bringing a sleeping bag - it gets a little chilly at night. Also my dad sometimes shows up, but that's usually only in times of great need.", rate: 30, owner_id: 2, lair_type: "fortress", room_type: "entire-hq", street_address: "101 St. Nicholas Drive", city: "North Pole", state: "AK", country: "USA", latitude: 64.7548317, longitude: -147.3431046, max_guests: 3},
  {title: "Daily Planet Office", description: "You won't find a less expensive place to stay in the heart of Metropolis! I am making that couch at my office at the Daily Planet available for you to rent while I'm out of town on some... errands. Given that the couch is in the middle of a working daily newspaper, there will always be someone around to keep you company and make you stick to your deadlines. Fair warning: a kid named Jimmy Olsen might try and take photos of you. ", rate: 20, owner_id: 2, lair_type: "office", room_type: "shared-room", street_address: "620 Eighth Avenue", city: "New York", state: "NY", country: "USA", latitude: 40.7562054, longitude: -73.9899143, max_guests: 1},
  {title: "Cozy Urban Dwelling", description: "All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.", rate: 10, owner_id: 9, lair_type: "underground", room_type: "shared-room", street_address: "183 Lorraine St", city: "Brooklyn", state: "NY", country: "USA", latitude: 40.6732938, longitude: -74.001732, max_guests: 10},
  {title: "The Matrix", description: "My house is just like any other house. But one day I realized that it was perhaps too much like the other houses. My neighbors look and act like me, but I can't get over this feeling that there's a bigger, unexplored world that I truly belong in. You can crash at my place while I search for answers. Free thinkers only, no suits.", rate: 30, owner_id: 13, lair_type: "underground", room_type: "entire-hq", street_address: "76 9th Ave", city: "New York", state: "NY", country: "USA", latitude: 40.7417806, longitude: -74.0045012, max_guests: 2}
])
User.create!([
  {first_name: "Bruce", last_name: "Wayne", email: "bwayne@aol.com", password_digest: "$2a$10$pJ1I5ckDMqnR/BWUTENFQOMMHrVxjGOi3tx3HU2rRS9PWBLbu87T2", session_token: "WDa+QJeKV/zA5XldjinUOHcV7S/O2EPMSVV8/w1znr0="},
  {first_name: "Clark", last_name: "Kent", email: "ckent@aol.com", password_digest: "$2a$10$CsEJduYFmkWJf8xrGBP4y./QnAwnBCkDuP/Uo7BVH0paxV.yxNUDe", session_token: "PzERDPYCaFa22ZTvwW/sLb39cUAt4pG7hzlfDjnHBwo="},
  {first_name: "Diana", last_name: "Prince", email: "dprince@aol.com", password_digest: "$2a$10$ZwK8U5FhsklgcLd7venHiuUth32/TMNcBpjjQlLkIiiR8rNyUv8Oi", session_token: "rVlerTPc3CyvKQ3+XbqSO6uqQLenYkKSdFSxLz+Cm1A="},
  {first_name: "Tony", last_name: "Stark", email: "tstark@aol.com", password_digest: "$2a$10$OtmGQdeCdzXkB/g/MG56VOG7NahqkdQp/QZ8QATbpB0Vh6m3MUs06", session_token: "zxUu9bcUbLt6Wy3E0aBGDL0XIVnUi+MLaJKFi4S1coI="},
  {first_name: "Steve", last_name: "Rogers", email: "srogers@aol.com", password_digest: "$2a$10$8oWHx15/tFo7okZxDZ8cDOtbekQScASQKiSDpWjkP6MXjZ67okwyK", session_token: "Wq8vDy8TH9Lopq2ATeSnIe18SiQuPB0qPOusPHhEJvc="},
  {first_name: "Ororo", last_name: "Munroe", email: "storm@aol.com", password_digest: "$2a$10$.oeYm4vaiXsO0nYnS5LnY.ac9Dd7/5y4YkHEX7tYV8deq0BeeQioC", session_token: "An2lf8+feXBpCKySeCK358lqKWHzg9oxlaggrtkQ6VQ="},
  {first_name: "Erik", last_name: "Lehnsherr", email: "elehnsherr@aol.com", password_digest: "$2a$10$PDcMxn0kI/oJbHZ8Lyk2c.TQAnrJ2OhNJ91HW/juWHVmFDgdP0qRe", session_token: "8c+W9c0ig8dG3aIsGvIjkfIfkxZDGrs/YM3f4LvvSaQ="},
  {first_name: "Dr", last_name: "Manhattan", email: "dmanhattan@aol.com", password_digest: "$2a$10$7DjFtw2yZatNeGK.LBToDu6hAg0dn2Tndn7UDVGMpxnmJjT9bM3/m", session_token: "dtJ104oK2dx0JdlMQY8cpzOS6V0DcaSF6pOfZ/SigvY="},
  {first_name: "The", last_name: "Joker", email: "misterj@aol.com", password_digest: "$2a$10$gfpBNb05TLVsiaoE5VwtfeVi0lShQFA7BtK17zEF372YefWCSvMzm", session_token: "ZqL04fvlqJ8eBSDuzRcwl5xSN3Z7zBvPB8wahfNFjC0="},
  {first_name: "Raven", last_name: "Darkhölme", email: "mystique@aol.com", password_digest: "$2a$10$RgfNIXrfTOvlg//YaMKt..YSoAsv4sMBpkAJ4hfUZ6Yhf2vNCuco.", session_token: "kAQ5ltludY9Nksc5aFy+JLXwkxQSlKTEtgo2/TQPFYo="},
  {first_name: "Barbara", last_name: "Gordon", email: "b_gordon@aol.com", password_digest: "$2a$10$rTzgqBOb4/TayF5g/gAm1.0G7QZYrNZ9GlyeqkQKlnEaKE.qnpWQ2", session_token: "LtGk75Mydzldojzjswxau2p/oUX4MXTMSmERsD303WI="},
  {first_name: "Laurie", last_name: "Juspeczyk", email: "silk_spectre@aol.com", password_digest: "$2a$10$QvEotjevRXsZIPsPOsIecO3ftrazyRDX6CMi8/aUS0XMnIKehO0GS", session_token: "LbCHFbCSWCTDGlAL0+kh/e0AXGVqp97c8UvEG3lhZw0="},
  {first_name: "Thomas", last_name: "Anderson", email: "neo@aol.com", password_digest: "$2a$10$gGtDDpFyHHRv5mWVZnE/nuT9lagn68yPOmJ1mismhA/oYpax.XEWW", session_token: "27u8egU7zaz6/FCjUV7mg9Mu/F65WA8qbcy5OMIGBA4="}
])
